[versions]
# Platform expectations
paper = "1.17.1-R0.1-SNAPSHOT"

# Annotations
annotations = "22.0.0"

# Plugins
fawe-bukkit = "1.17-291"

# Third party
serverlib = "2.3.0"
bstats = "2.2.1"
paperlib = "1.0.6"

# Gradle plugins
shadow = "7.0.0"
grgit = "4.1.0"
pluginyml = "0.5.0"

[libraries]
# Platform expectations
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# Annotations
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# Plugins
faweBukkit = { group = "com.fastasyncworldedit", name = "FastAsyncWorldEdit-Bukkit", version.ref = "fawe-bukkit" }

# Third party
serverlib = { group = "dev.notmyfault.serverlib", name = "ServerLib", version.ref = "serverlib" }
bstatsBase = { group = "org.bstats", name = "bstats-base", version.ref = "bstats" }
bstatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
paperlib = { group = "io.papermc", name = "paperlib", version.ref = "paperlib" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
