[versions]
# Annotations
annotations = "26.0.2-1"

# Cloud command system
cloud = "1.8.4"

# Gradle plugins
shadow = "9.3.1"
pluginyml = "0.6.0"
publish = "0.35.0"
minotaur = "2.8.10"
hangar = "0.1.4"
runPaper = "3.0.2"
paperApi = "1.21.4-R0.1-SNAPSHOT"

[libraries]

# Annotations
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# Paper
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }

# Cloud command system
cloudcore = { group = "cloud.commandframework", name = "cloud-core", version.ref = "cloud" }
cloudannotations = { group = "cloud.commandframework", name = "cloud-annotations", version.ref = "cloud" }
cloudbukkit = { group = "cloud.commandframework", name = "cloud-bukkit", version.ref = "cloud" }
cloudpaper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
