[versions]
# Annotations
annotations = "24.1.0"

# Cloud command system
cloud = "1.8.4"

# Gradle plugins
shadow = "8.3.2"
pluginyml = "0.6.0"
nexus = "2.0.0"
minotaur = "2.8.7"
hangar = "0.1.2"
runPaper = "2.3.1"

[libraries]

# Annotations
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# Cloud command system
cloudcore = { group = "cloud.commandframework", name = "cloud-core", version.ref = "cloud" }
cloudannotations = { group = "cloud.commandframework", name = "cloud-annotations", version.ref = "cloud" }
cloudbukkit = { group = "cloud.commandframework", name = "cloud-bukkit", version.ref = "cloud" }
cloudpaper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
